Models/Location.cs
using System.ComponentModel.DataAnnotations;

namespace TourView.Models
{
    public class Location
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [StringLength(100, ErrorMessage = "The maximum length must be 100 characters")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string? Description { get; set; }


        [Required(ErrorMessage = "Address is required")]
        public string? Address { get; set; }

        [Required(ErrorMessage = "Phone number is required")]
        public string? PhoneNumber { get; set; }


        [Required(ErrorMessage = "Schedule is required")]
        public string? Schedule { get; set; }

        [Required(ErrorMessage = "Menu is required")]
        public string? Menu { get; set; }

        public string? PhotoUrl { get; set; }
        public double? Rating { get; set; }
        public string? ManagerId { get; set; }

        // public List<string> Cuisine { get; set; }


    }

}

Controllers/LocationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using TourView.Data;
using TourView.Models;

namespace TourView.Controllers
{
    public class LocationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private IWebHostEnvironment _env;

        public LocationController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager, IWebHostEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }

        [HttpGet]
        [Authorize(Roles = "User, Editor, Admin")]
        public async Task<IActionResult> Index(string name, string? description, string? address)
        {
            ViewData["CurrentName"] = name;
            ViewData["CurrentDescription"] = description;
            ViewData["CurrentAddress"] = address;
            ViewBag.reviews = await _context.Reviews.ToListAsync();
            // Logic for search bars
            var locations = from b in _context.Locations
                            select b;
            if (!String.IsNullOrEmpty(name))
            {
                locations = locations.Where(b => b.Name.Contains(name));
            }
            if (!String.IsNullOrEmpty(description))
            {
                locations = locations.Where(b => b.Description.Contains(description));
            }
            if (!String.IsNullOrEmpty(address))
            {
                locations = locations.Where(b => b.Address.Contains(address));
            }

            return View(await locations.ToListAsync());
        }

        [Authorize(Roles = "User, Editor, Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Location location = await _context.Locations.FirstOrDefaultAsync(m => m.Id == id);

            if (location == null)
            {
                return NotFound();
            }
            MyViewModel mvm = new MyViewModel();
            mvm.location = location;
            // Reservations needed for the notification of unseen reservations (for manager)
            mvm.reservationsIEn = _context.Reservations.Where(r => r.LocationId == location.Id)
                                                        .Where(r => r.ReservationDate > DateTime.Now);
            // Checking if user is manager (the check is made in the view)
            string locationManager = _context.Users.First(u => u.Id == location.ManagerId).Id;
            ViewBag.managerName = _context.Users.First(u => u.Id == locationManager).UserName;
            return View(mvm);
        }


        [Authorize(Roles = "Editor")]
        public IActionResult Create()
        {
            string userId = _userManager.GetUserId(User);
            try
            {
                int? loc = _context.Locations.First(l => l.ManagerId == userId).Id;
                return RedirectToAction("Details", new { id = loc });
            }
            catch (Exception)
            {
                return View();
            }          

        }
     

        [HttpPost]
        //[ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Create(Location location, IFormFile locationImage)
        {
            location.ManagerId = _userManager.GetUserId(User);
            if (locationImage != null && locationImage.Length > 0)  
            {
                var storagePath = Path.Combine(
                    _env.WebRootPath,
                    "images",
                    locationImage.FileName);
                var databaseFileName = "/images/" + locationImage.FileName;
                using(var fileStream = new FileStream(storagePath, FileMode.Create))
                {
                    await locationImage.CopyToAsync(fileStream);
                }
                location.PhotoUrl = databaseFileName;
            }


            if (ModelState.IsValid) 
            {
                
                _context.Add(location);
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(location);


        }


        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var locationFromDb = await _context.Locations.FirstOrDefaultAsync(loc => loc.Id == id);
            if (locationFromDb == null)
            {
                return NotFound();
            }
            ViewData["locationId"] = id;
            return View(locationFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> EditPOST(int id, IFormFile locationImage, [Bind("Id,Name,Description,Address,PhoneNumber,Schedule,Menu,PhotoUrl,Rating")] Location location)
        {
            location.Id = id;
            location.ManagerId = _context.Users.First(u => u.UserName == User.Identity.Name).Id;
            if (locationImage.Length > 0)
            {
                var storagePath = Path.Combine(
                    _env.WebRootPath,
                    "images",
                    locationImage.FileName);
                var databaseFileName = "/images/" + locationImage.FileName;
                using (var fileStream = new FileStream(storagePath, FileMode.Create))
                {
                    await locationImage.CopyToAsync(fileStream);
                }
                location.PhotoUrl = databaseFileName;
            }
            if (ModelState.IsValid)
            {
                _context.Update(location);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        [Authorize(Roles = "Editor,Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) { return NotFound(); }

            var location = await _context.Locations.FirstOrDefaultAsync(m => m.Id == id);
            if (location == null) { return NotFound(); }

            return View(location);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor,Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _context.Locations.FindAsync(id);
            _context.Locations.Remove(location);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.Id == id);
        }
    }
}

Controllers/ReservationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TourView.Data;
using TourView.Models;

namespace TourView.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ReservationController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(int locationId)
        {
            DateTime now = DateTime.Now;
            // Taking reservations for specific location + not earlier than current time/date
            var reservations = await _context.Reservations.Where(r => r.LocationId == locationId && r.ReservationDate > now).ToListAsync();
            MyViewModel mvm = new MyViewModel();
            mvm.reservationsIEn = reservations;
            mvm.users = _context.Users;
            ViewData["location"] = _context.Locations.Find(locationId).Name;
            return View(mvm);
        }

        public IActionResult Create(int locationId)
        {
            ViewData["locationId"] = locationId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Reservation reservation)
        {
            reservation.UserId = _userManager.GetUserId(User);

            _context.Add(reservation);
            _context.SaveChanges();
            return RedirectToAction("Details","Location", new { Id = reservation.LocationId });

        }

        public IActionResult SetSeen(int Id) 
        {
            int tempId = Id;
            var reservation = _context.Reservations.FirstOrDefault(r => r.Id == tempId);
            reservation.seen = true;
            _context.SaveChanges();
            return RedirectToAction("Index", new { locationId = reservation.LocationId});
        }
    }
}

Controllers/ReviewController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TourView.Data;
using TourView.Models;

namespace TourView.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ReviewController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(int locationId)
        {

            IEnumerable<Review> reviews = await _context.Reviews.Where(r => r.LocationId == locationId).ToListAsync();
            Location location = _context.Locations.First(loc => loc.Id == locationId);
            ViewData["location"] = location.Name;
            ViewData["locationId"] = location.Id;
            MyViewModel myViewModel = new MyViewModel();
            myViewModel.users = _context.Users;
            myViewModel.reviewsIEn = reviews;
            return View(myViewModel);
        }

        public IActionResult Create(int locationId)
        {
            ViewBag.locationId = locationId;
            Location location = _context.Locations.First(loc => loc.Id == locationId);
            ViewData["location"] = location.Name;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Review review)
        {
            ApplicationUser user = _context.Users.First(u => u.UserName == User.Identity.Name);
            review.User = user;
            review.UserId = user.Id;
            review.Location = _context.Locations.Find(review.LocationId);
            if (ModelState.IsValid)
            {
                _context.Add(review);
                _context.SaveChanges();
                return RedirectToAction("Index", new { locationId = review.LocationId });
            }

            Location location = _context.Locations.First(loc => loc.Id == review.LocationId);
            ViewData["location"] = location.Name;
            return View(review);
        }

        public async Task<IActionResult> Edit(int? reviewId)
        {
            if (reviewId == null || reviewId == 0)
            {
                return NotFound();
            }
            var reviewFromDb = await _context.Reviews.FirstOrDefaultAsync(rev => rev.Id == reviewId);
            if (reviewFromDb == null)
            {
                return NotFound();
            }
            ViewData["reviewId"] = reviewId;
            var locationId = _context.Reviews.Find(reviewId).LocationId;
            ViewData["locationId"] = locationId;
            ViewData["location"] = _context.Locations.Find(locationId).Name;
            return View(reviewFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPOST(int reviewId, Review review)
        {
            var id = reviewId;
            review.User = _context.Users.First(u => u.UserName == User.Identity.Name);
            review.Id = id;
            if (ModelState.IsValid)
            {
                _context.Update(review);
                _context.SaveChanges();

                return RedirectToAction("Index", new { locationId = review.LocationId });
            }
            return View(review);
        }

        public async Task<IActionResult> Delete(int? reviewId)
        {
            if (reviewId == null || reviewId == 0)
            {
                return NotFound();
            }
            var reviewFromDb = await _context.Reviews.FirstOrDefaultAsync(rev => rev.Id == reviewId);
            if (reviewFromDb == null)
            {
                return NotFound();
            }
            ViewData["reviewId"] = reviewId;
            var locationId = _context.Reviews.Find(reviewId).LocationId;
            ViewData["locationId"] = locationId;
            ViewData["location"] = _context.Locations.Find(locationId).Name;
            return View(reviewFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int reviewId)
        {
            var review = _context.Reviews.Find(reviewId);
            if (review == null)
            {
                return NotFound();
            }
            _context.Remove(review);
            _context.SaveChanges();
            return RedirectToAction("Index", new { locationId = review.LocationId });


        }
    }
}

Views/Location/Create.cshtml
@model TourView.Models.Location

@{
    ViewData["Title"] = "TourView - Add your Location";
}
@if (TempData.Peek("message") != null)
{
    <div class="alert alert-info">
        @TempData.Peek("message")
    </div>
}

<form method="post" enctype="multipart/form-data" asp-controller="Location" asp-action="Create">
    <div asp-validation-summary="All"></div>
    <div>
        <label asp-for="Name">Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Description">Description</label>
        <input asp-for="Description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Address">Address</label>
        <input asp-for="Address" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="PhoneNumber">Phone Number</label>
        <input asp-for="PhoneNumber" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Schedule">Schedule</label>
        <input asp-for="Schedule" />
        <span asp-validation-for="Schedule" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Menu">Menu</label>
        <input asp-for="Menu" />
        <span asp-validation-for="Menu" class="text-danger"></span>
    </div>
    <div>
        <input class="form-control" type="file" name="locationImage" required />
    </div>

    <button type="submit">Submit</button>
    <a asp-controller="Home" asp-action="Index">Back to home</a>
</form>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Location/Delete.cshtml
@model TourView.Models.Location

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Schedule)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Schedule)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Menu)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Menu)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Location/Details.cshtml
@model MyViewModel
@{
    ViewData["title"] = "TourView - Location Details";
    bool hasNotSeen = Model.reservationsIEn.Any(entry => entry.seen != true);
    var hNS = 0;
    if (hasNotSeen)
    {
        hNS = 1;
    }
}
<h2>@Model.location.Name</h2>

<div>
    <h4>Address:</h4>
    <p>@Model.location.Address</p>
</div>
<div>
    <h4>Phone Number:</h4>
    <p>@Model.location.PhoneNumber</p>
</div>
<div>
    <h4>Schedule:</h4>
    <p>@Model.location.Schedule</p>
</div>
<div>
    <h4>Menu:</h4>
    <p>@Model.location.Menu</p>
</div>
@if (Model.location.PhotoUrl != null)
{
    <div>
        <h4>Photo:</h4>
        <img src="@Model.location.PhotoUrl" alt=" no photo yet" width="400px" />
    </div>
}
<a asp-controller="Review" asp-action="Index" asp-route-locationId="@Model.location.Id">View Reviews</a>
@if (User.Identity.Name == ViewBag.managerName)
{
    <div></div>
    <a asp-controller="Reservation" asp-action="Index" asp-route-locationId="@Model.location.Id">View Reservations for Your Location</a>
    <div></div>
    <a asp-controller="Location" asp-action="Edit" asp-route-Id="@Model.location.Id">Edit Your Location</a>
    <a asp-controller="Location" asp-action="Delete" asp-route-Id="@Model.location.Id">Delete Your Location</a>    
}
else
{
    <a asp-controller="Reservation" asp-action="Create" asp-route-locationId="@Model.location.Id">Make a Reservation</a>
}

@if (User.Identity.Name == ViewBag.managerName) 
{ // when opening details about your own location you get notified if you have unseen reservations | hNS gets the value of one (top of the view) because of unknown problems with bool in the js script
    <script>
        if(@hNS == 1){   
            alert("You have unseen reservations!");
        }


    </script>
}

Views/Location/Edit.cshtml
@model TourView.Models.Location

@{
    ViewData["Title"] = "Edit";
    var id = ViewData["locationId"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<form method="post" enctype="multipart/form-data" asp-action="EditPOST" asp-route-locationId="@id">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address" class="control-label"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label"></label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Schedule" class="control-label"></label>
        <input asp-for="Schedule" class="form-control" />
        <span asp-validation-for="Schedule" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Menu" class="control-label"></label>
        <input asp-for="Menu" class="form-control" />
        <span asp-validation-for="Menu" class="text-danger"></span>
    </div>
    <div>
        <input class="form-control" type="file" name="locationImage" required />
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Location/Index.cshtml
@model IEnumerable<Location>
@{
    ViewData["Title"] = "TourView - All locations";
    IEnumerable<Review> reviews = ViewBag.reviews;
}

@if (ViewBag.Msg != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Msg
    </div>
}

<h2>Locations</h2>
<form asp-action="Index" method="get">
    <div class="form-group">
        <label for="name">Search by name:</label>
        <input type="text" name="name" value="@ViewData["CurrentName"]" />
    </div>
    <br />
    <div class="form-group">
        <label for="description">Search by description:</label>
        <input type="text" name="description" value="@ViewData["CurrentDescription"]" />
    </div>
    <br />
    <div class="form-group">
        <label for="address">Search by address:</label>
        <input type="text" name="address" value="@ViewData["CurrentAddress"]" />
    </div>
    <br />
    <div>
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

<a asp-action="Index">Back to full list</a>
<hr />




<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Rating</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var location in Model)
        {
            IEnumerable<Review> locReviews = reviews.Where(r => r.LocationId == location.Id);
            double ratingAvg = 0.0;
            int ratingCount = 0;
            foreach (var review in locReviews)
            {
                ratingAvg = ratingAvg + review.Rating;
                ratingCount += 1;
            }
            ratingAvg = ratingAvg / ratingCount;
            ratingAvg = Math.Round(ratingAvg, 2);

            <tr>
                <td width="20%">
                    <a href="@Url.Action("Details", "Location", new { id = location.Id })">@location.Name</a>
                </td>
                <td width="60%">@location.Description</td>
                @if (ratingCount != 0)
                {
                    <td width="20%">@ratingAvg</td>
                }
                else
                {
                    <td width="20%">No Ratings</td>
                }

            </tr>
        }
    </tbody>

</table>