Controllers/AdminPanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using TourView.Data;
using TourView.Models;

namespace TourView.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public AdminPanelController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager) 
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            MyViewModel mvm = new MyViewModel();
            
            IEnumerable<ApplicationUser> users = await _context.Users.ToListAsync();
            mvm.usersIEn = users;
            IEnumerable<Location> locations = await _context.Locations.ToListAsync();
            mvm.locationsIEn = locations.Reverse();
            IEnumerable<Review> reviews = await _context.Reviews.ToListAsync();
            mvm.reviewsIEn = reviews.Reverse();
            // Passing the three lists from the db, reverse() for showing latest ones ( reversing by id but they increment so it is still the latest)
            return View(mvm);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AllReviews()
        {
            MyViewModel mvm = new MyViewModel();
            IEnumerable<ApplicationUser> users = await _context.Users.ToListAsync();
            mvm.usersIEn = users;
            IEnumerable<Location> locations = await _context.Locations.ToListAsync();
            mvm.locationsIEn = locations.Reverse();
            IEnumerable<Review> reviews = await _context.Reviews.ToListAsync();
            mvm.reviewsIEn = reviews.Reverse();
            //Same as Index => location and users are instead used to show the reviewed location and the reviewer
            return View(mvm);
        }

        public async Task<IActionResult> AllLocations()
        {
            MyViewModel mvm = new MyViewModel();
            IEnumerable<Location> locations = await _context.Locations.ToListAsync();
            mvm.locationsIEn = locations.Reverse();
            // Reversed list for locations - latest locations
            return View(mvm);
        }

        public async Task<IActionResult> RolesPanel()
        {
            MyViewModel mvm = new MyViewModel();
            IEnumerable<ApplicationUser> users = await _context.Users.ToListAsync();
            mvm.usersIEn = users;
            
            //joining user, role and userid-roleid
            var userRoles = await _context.UserRoles.ToListAsync();
            var roles = await _context.Roles.ToListAsync();
            var userWithRoles = from userRole in userRoles
                                join role in roles on userRole.RoleId equals role.Id
                                join user in users on userRole.UserId equals user.Id into userGroup
                                from user in userGroup.DefaultIfEmpty()
                                select new
                                {
                                    UserId = userRole.UserId,
                                    RoleId = userRole.RoleId,
                                    RoleName = role.Name,
                                    UserName = user != null ? user.UserName : string.Empty
                                };
            ViewBag.userWithRoles = userWithRoles;
            return View(mvm);
        }

        public async Task<IActionResult> SetManager(string userId)
        {
            ApplicationUser user = await _context.Users.FindAsync(userId);
            await _userManager.AddToRoleAsync(user, "Editor");    // Change to manager when manager is added // Update: manager is only for frontend, backend he is still considered "editor"
            return RedirectToAction("RolesPanel");
        }

        
    }
}

Controllers/LocationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using TourView.Data;
using TourView.Models;

namespace TourView.Controllers
{
    public class LocationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private IWebHostEnvironment _env;

        public LocationController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager, IWebHostEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }

        [HttpGet]
        [Authorize(Roles = "User, Editor, Admin")]
        public async Task<IActionResult> Index(string name, string? description, string? address)
        {
            ViewData["CurrentName"] = name;
            ViewData["CurrentDescription"] = description;
            ViewData["CurrentAddress"] = address;
            ViewBag.reviews = await _context.Reviews.ToListAsync();
            // Logic for search bars
            var locations = from b in _context.Locations
                            select b;
            if (!String.IsNullOrEmpty(name))
            {
                locations = locations.Where(b => b.Name.Contains(name));
            }
            if (!String.IsNullOrEmpty(description))
            {
                locations = locations.Where(b => b.Description.Contains(description));
            }
            if (!String.IsNullOrEmpty(address))
            {
                locations = locations.Where(b => b.Address.Contains(address));
            }

            return View(await locations.ToListAsync());
        }

        [Authorize(Roles = "User, Editor, Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Location location = await _context.Locations.FirstOrDefaultAsync(m => m.Id == id);

            if (location == null)
            {
                return NotFound();
            }
            MyViewModel mvm = new MyViewModel();
            mvm.location = location;
            // Reservations needed for the notification of unseen reservations (for manager)
            mvm.reservationsIEn = _context.Reservations.Where(r => r.LocationId == location.Id)
                                                        .Where(r => r.ReservationDate > DateTime.Now);
            // Checking if user is manager (the check is made in the view)
            string locationManager = _context.Users.First(u => u.Id == location.ManagerId).Id;
            ViewBag.managerName = _context.Users.First(u => u.Id == locationManager).UserName;
            return View(mvm);
        }


        [Authorize(Roles = "Editor")]
        public IActionResult Create()
        {
            string userId = _userManager.GetUserId(User);
            try
            {
                int? loc = _context.Locations.First(l => l.ManagerId == userId).Id;
                return RedirectToAction("Details", new { id = loc });
            }
            catch (Exception)
            {
                return View();
            }          

        }
     

        [HttpPost]
        //[ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Create(Location location, IFormFile locationImage)
        {
            location.ManagerId = _userManager.GetUserId(User);
            if (locationImage != null && locationImage.Length > 0)  
            {
                var storagePath = Path.Combine(
                    _env.WebRootPath,
                    "images",
                    locationImage.FileName);
                var databaseFileName = "/images/" + locationImage.FileName;
                using(var fileStream = new FileStream(storagePath, FileMode.Create))
                {
                    await locationImage.CopyToAsync(fileStream);
                }
                location.PhotoUrl = databaseFileName;
            }


            if (ModelState.IsValid) 
            {
                
                _context.Add(location);
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(location);


        }


        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var locationFromDb = await _context.Locations.FirstOrDefaultAsync(loc => loc.Id == id);
            if (locationFromDb == null)
            {
                return NotFound();
            }
            ViewData["locationId"] = id;
            return View(locationFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> EditPOST(int id, IFormFile locationImage, [Bind("Id,Name,Description,Address,PhoneNumber,Schedule,Menu,PhotoUrl,Rating")] Location location)
        {
            location.Id = id;
            location.ManagerId = _context.Users.First(u => u.UserName == User.Identity.Name).Id;
            if (locationImage.Length > 0)
            {
                var storagePath = Path.Combine(
                    _env.WebRootPath,
                    "images",
                    locationImage.FileName);
                var databaseFileName = "/images/" + locationImage.FileName;
                using (var fileStream = new FileStream(storagePath, FileMode.Create))
                {
                    await locationImage.CopyToAsync(fileStream);
                }
                location.PhotoUrl = databaseFileName;
            }
            if (ModelState.IsValid)
            {
                _context.Update(location);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        [Authorize(Roles = "Editor,Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) { return NotFound(); }

            var location = await _context.Locations.FirstOrDefaultAsync(m => m.Id == id);
            if (location == null) { return NotFound(); }

            return View(location);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor,Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _context.Locations.FindAsync(id);
            _context.Locations.Remove(location);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.Id == id);
        }
    }
}

Controllers/ReviewController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TourView.Data;
using TourView.Models;

namespace TourView.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ReviewController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(int locationId)
        {

            IEnumerable<Review> reviews = await _context.Reviews.Where(r => r.LocationId == locationId).ToListAsync();
            Location location = _context.Locations.First(loc => loc.Id == locationId);
            ViewData["location"] = location.Name;
            ViewData["locationId"] = location.Id;
            MyViewModel myViewModel = new MyViewModel();
            myViewModel.users = _context.Users;
            myViewModel.reviewsIEn = reviews;
            return View(myViewModel);
        }

        public IActionResult Create(int locationId)
        {
            ViewBag.locationId = locationId;
            Location location = _context.Locations.First(loc => loc.Id == locationId);
            ViewData["location"] = location.Name;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Review review)
        {
            ApplicationUser user = _context.Users.First(u => u.UserName == User.Identity.Name);
            review.User = user;
            review.UserId = user.Id;
            review.Location = _context.Locations.Find(review.LocationId);
            if (ModelState.IsValid)
            {
                _context.Add(review);
                _context.SaveChanges();
                return RedirectToAction("Index", new { locationId = review.LocationId });
            }

            Location location = _context.Locations.First(loc => loc.Id == review.LocationId);
            ViewData["location"] = location.Name;
            return View(review);
        }

        public async Task<IActionResult> Edit(int? reviewId)
        {
            if (reviewId == null || reviewId == 0)
            {
                return NotFound();
            }
            var reviewFromDb = await _context.Reviews.FirstOrDefaultAsync(rev => rev.Id == reviewId);
            if (reviewFromDb == null)
            {
                return NotFound();
            }
            ViewData["reviewId"] = reviewId;
            var locationId = _context.Reviews.Find(reviewId).LocationId;
            ViewData["locationId"] = locationId;
            ViewData["location"] = _context.Locations.Find(locationId).Name;
            return View(reviewFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPOST(int reviewId, Review review)
        {
            var id = reviewId;
            review.User = _context.Users.First(u => u.UserName == User.Identity.Name);
            review.Id = id;
            if (ModelState.IsValid)
            {
                _context.Update(review);
                _context.SaveChanges();

                return RedirectToAction("Index", new { locationId = review.LocationId });
            }
            return View(review);
        }

        public async Task<IActionResult> Delete(int? reviewId)
        {
            if (reviewId == null || reviewId == 0)
            {
                return NotFound();
            }
            var reviewFromDb = await _context.Reviews.FirstOrDefaultAsync(rev => rev.Id == reviewId);
            if (reviewFromDb == null)
            {
                return NotFound();
            }
            ViewData["reviewId"] = reviewId;
            var locationId = _context.Reviews.Find(reviewId).LocationId;
            ViewData["locationId"] = locationId;
            ViewData["location"] = _context.Locations.Find(locationId).Name;
            return View(reviewFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int reviewId)
        {
            var review = _context.Reviews.Find(reviewId);
            if (review == null)
            {
                return NotFound();
            }
            _context.Remove(review);
            _context.SaveChanges();
            return RedirectToAction("Index", new { locationId = review.LocationId });


        }
    }
}

Views/AdminPanel/AllLocations.cshtml
@{
    ViewData["Title"] = "Admin Panel - All Locations";
}

<h3>Latest added locations</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Address</th>
            <th>PhoneNumber</th>
            <th>Schedule</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var location in Model.locationsIEn)
        {
            <tr>
                <td width="18%">@location.Name</td>
                <td width="40%">@location.Description</td>
                <td width="14%">@location.Address</td>
                <td width="14%">@location.PhoneNumber</td>
                <td width="14%">@location.Schedule</td>
                <td><a asp-controller="Location" asp-action="Delete" asp-route-Id="@location.Id">delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/AdminPanel/AllReviews.cshtml
@model TourView.Models.MyViewModel
@{
    ViewData["Title"] = "Admin Panel - All Reviews";
}

<h3>All added reviews</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Comment</th>
            <th>Rating</th>
            <th>Loc. Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var review in Model.reviewsIEn)
        {
            <tr>
                <td width="20%">@Model.usersIEn.First(u => u.Id == review.UserId)</td>
                <td width="60%">@review.Comment</td>
                <td>@review.Rating/5</td>
                <td>@Model.locationsIEn.First(loc => loc.Id == review.LocationId).Name</td>
                <td><a asp-controller="Review" asp-action="Delete" asp-route-reviewId="@review.Id">delete</a></td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="AdminPanel" asp-action="Index" >Back to Overview</a>

Views/AdminPanel/Index.cshtml
@model TourView.Models.MyViewModel
@{
    ViewData["Title"] = "Admin Panel";
    var revCount = 0;
    var locCount = 0;

}
<h1 class="text-center">Admin Panel Overview</h1>
<h1>Hello @User.Identity?.Name</h1>
<h3><a asp-controller="AdminPanel" asp-action="RolesPanel">Go to Roles Panel</a></h3>

<h3>Latest added reviews</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Comment</th>
            <th>Rating</th>
            <th>Loc. Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var review in Model.reviewsIEn)
        {
            if (revCount == 7)
            {
                break;
            }
            else
            {
                revCount += 1;
            }
            <tr>
                <td width="20%">@Model.usersIEn.First(u => u.Id == review.UserId)</td>
                <td width="60%">@review.Comment</td>
                <td >@review.Rating/5</td>
                <td width="13%">@Model.locationsIEn.First(loc => loc.Id == review.LocationId).Name</td>
                <td width="5%"><a asp-controller="Review" asp-action="Delete" asp-route-reviewId="@review.Id">delete</a></td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="AdminPanel" asp-action="AllReviews">See all reviews</a>
<div>&nbsp;</div>
<h3>Latest added locations</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Schedule</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var location in Model.locationsIEn)
        {
            if (locCount == 7)
            {
                break;
            }
            else
            {
                locCount += 1;
            }
            <tr>
                <td width="20%">@location.Name</td>
                <td width="40%">@location.Description</td>
                <td width="13%">@location.Address</td>
                <td width="10%">@location.PhoneNumber</td>
                <td width="13%">@location.Schedule</td>
                <td width="5%"><a asp-controller="Location" asp-action="Delete" asp-route-Id="@location.Id">delete</a></td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="AdminPanel" asp-action="AllLocations">See all locations</a>

Views/AdminPanel/RolesPanel.cshtml
@model TourView.Models.MyViewModel
@{
    ViewData["Title"] = "Admin Panel - Roles Panel";
    }
<h3>Registered users</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>UserID</th>
            <th>Role</th>
            <th>Set as Manager</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in ViewBag.userWithRoles)
        {
            <tr>
                <td>@user.UserName</td>
                <td>@user.UserId</td>
                @if(user.RoleName == "Editor")
                {
                    <td>Manager</td>
                }
                else
                {
                    <td>@user.RoleName</td>
                }
                
                @if(user.RoleName == "User")
                {
                    <td><a asp-controller="AdminPanel" asp-action="SetManager" asp-route-userId="@user.UserId">Set as Manager</a></td>
                }
                else
                {
                    <td>-</td>
                }
                
            </tr>
        }
    </tbody>
</table>